package com.dawood.orbit.tools.password

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import com.dawood.orbit.core.designsystem.component.OrbitBadge
import com.dawood.orbit.core.designsystem.component.OrbitButton
import com.dawood.orbit.core.designsystem.component.OrbitButtonSize
import com.dawood.orbit.core.designsystem.component.OrbitButtonVariant
import com.dawood.orbit.core.designsystem.component.OrbitCard
import com.dawood.orbit.core.designsystem.component.OrbitProgressBar
import com.dawood.orbit.core.designsystem.component.OrbitSettingRow
import com.dawood.orbit.core.designsystem.component.OrbitSwitch
import com.dawood.orbit.core.designsystem.component.OrbitText
import com.dawood.orbit.core.designsystem.component.OrbitTone
import com.dawood.orbit.core.designsystem.component.contentColor
import com.dawood.orbit.core.designsystem.icon.OrbitIcons
import com.dawood.orbit.core.designsystem.theme.OrbitTheme
import com.dawood.orbit.core.layout.OrbitContentContainer
import com.dawood.orbit.tools.model.Tool
import com.dawood.orbit.tools.shell.ToolFooter
import com.dawood.orbit.tools.shell.ToolShell
import com.dawood.orbit.tools.shell.ToolWorkspace

/**
 * Password Generator.
 *
 * Nothing is stored: a generated password lives on screen until it is replaced.
 * Keeping a vault would need encryption at rest and a key the app does not have
 * yet, and a fake vault is worse than none.
 */
@Composable
fun PasswordGeneratorTool(
    tool: Tool,
    onBack: () -> Unit,
    modifier: Modifier = Modifier,
) {
    val clipboard = LocalClipboardManager.current
    var options by remember { mutableStateOf(PasswordGenerator.Options()) }
    var generated by remember { mutableStateOf<PasswordGenerator.Generated?>(null) }
    var copied by remember { mutableStateOf(false) }

    // Regenerate whenever the settings change so the preview always matches
    // what the switches say.
    LaunchedEffect(options) {
        generated = PasswordGenerator.generate(options)
        copied = false
    }

    val entropy = generated?.entropyBits ?: 0
    val strength = PasswordGenerator.strengthLabel(entropy)
    val tone = when {
        entropy < 45 -> OrbitTone.Error
        entropy < 70 -> OrbitTone.Warning
        entropy < 100 -> OrbitTone.Accent
        else -> OrbitTone.Success
    }

    ToolShell(
        tool = tool,
        onBack = onBack,
        modifier = modifier,
        subtitle = if (generated == null) "Pick at least one character set" else "$strength · $entropy bits",
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .padding(OrbitTheme.spacing.lg),
        ) {
            OrbitContentContainer(maxWidth = 680.dp) {
                Column(verticalArrangement = Arrangement.spacedBy(OrbitTheme.spacing.lg)) {

                    OrbitCard(color = OrbitTheme.colors.surfaceSunken) {
                        Column(
                            modifier = Modifier.fillMaxWidth(),
                            verticalArrangement = Arrangement.spacedBy(OrbitTheme.spacing.md),
                        ) {
                            OrbitText(
                                text = generated?.password ?: "Switch on a character set",
                                style = OrbitTheme.typography.mono.copy(fontSize = OrbitTheme.typography.h2.fontSize),
                                color = OrbitTheme.colors.textPrimary,
                                modifier = Modifier.fillMaxWidth(),
                                textAlign = TextAlign.Center,
                                maxLines = 4,
                            )
                            OrbitProgressBar(
                                progress = (entropy / 128f).coerceIn(0f, 1f),
                                color = tone.contentColor(),
                            )
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.spacedBy(OrbitTheme.spacing.sm),
                            ) {
                                OrbitBadge(strength, tone = tone, showDot = true)
                                OrbitText(
                                    text = "$entropy bits · pool of ${generated?.poolSize ?: 0}",
                                    style = OrbitTheme.typography.caption,
                                    color = OrbitTheme.colors.textMuted,
                                    modifier = Modifier.weight(1f),
                                )
                            }
                            Row(horizontalArrangement = Arrangement.spacedBy(OrbitTheme.spacing.sm)) {
                                OrbitButton(
                                    text = if (copied) "Copied" else "Copy",
                                    onClick = {
                                        generated?.let {
                                            clipboard.setText(AnnotatedString(it.password))
                                            copied = true
                                        }
                                    },
                                    leadingIcon = if (copied) OrbitIcons.Check else OrbitIcons.Copy,
                                    enabled = generated != null,
                                )
                                OrbitButton(
                                    text = "Generate again",
                                    onClick = {
                                        generated = PasswordGenerator.generate(options)
                                        copied = false
                                    },
                                    variant = OrbitButtonVariant.Secondary,
                                    leadingIcon = OrbitIcons.Refresh,
                                )
                            }
                        }
                    }

                    ToolWorkspace(label = "Length") {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(OrbitTheme.spacing.sm),
                        ) {
                            OrbitButton(
                                text = "−",
                                onClick = { options = options.copy(length = (options.length - 1).coerceAtLeast(PasswordGenerator.MIN_LENGTH)) },
                                variant = OrbitButtonVariant.Secondary,
                                size = OrbitButtonSize.Small,
                            )
                            OrbitText(
                                text = "${options.length} characters",
                                style = OrbitTheme.typography.h3,
                                modifier = Modifier.weight(1f),
                                textAlign = TextAlign.Center,
                            )
                            OrbitButton(
                                text = "+",
                                onClick = { options = options.copy(length = (options.length + 1).coerceAtMost(PasswordGenerator.MAX_LENGTH)) },
                                variant = OrbitButtonVariant.Secondary,
                                size = OrbitButtonSize.Small,
                            )
                        }
                        Row(horizontalArrangement = Arrangement.spacedBy(OrbitTheme.spacing.sm)) {
                            listOf(12, 16, 20, 32).forEach { preset ->
                                OrbitButton(
                                    text = "$preset",
                                    onClick = { options = options.copy(length = preset) },
                                    variant = OrbitButtonVariant.Ghost,
                                    size = OrbitButtonSize.Small,
                                )
                            }
                        }
                    }

                    OrbitCard(contentPadding = androidx.compose.foundation.layout.PaddingValues(OrbitTheme.spacing.xs)) {
                        OrbitSettingRow(
                            title = "Lowercase",
                            description = "a to z",
                            trailing = {
                                OrbitSwitch(
                                    checked = options.lowercase,
                                    onCheckedChange = { options = options.copy(lowercase = it) },
                                )
                            },
                        )
                        OrbitSettingRow(
                            title = "Uppercase",
                            description = "A to Z",
                            trailing = {
                                OrbitSwitch(
                                    checked = options.uppercase,
                                    onCheckedChange = { options = options.copy(uppercase = it) },
                                )
                            },
                        )
                        OrbitSettingRow(
                            title = "Digits",
                            description = "0 to 9",
                            trailing = {
                                OrbitSwitch(
                                    checked = options.digits,
                                    onCheckedChange = { options = options.copy(digits = it) },
                                )
                            },
                        )
                        OrbitSettingRow(
                            title = "Symbols",
                            description = "! @ # and friends",
                            trailing = {
                                OrbitSwitch(
                                    checked = options.symbols,
                                    onCheckedChange = { options = options.copy(symbols = it) },
                                )
                            },
                        )
                        OrbitSettingRow(
                            title = "Avoid look-alike characters",
                            description = "Drops I l 1 O 0 o and quotes",
                            trailing = {
                                OrbitSwitch(
                                    checked = options.avoidAmbiguous,
                                    onCheckedChange = { options = options.copy(avoidAmbiguous = it) },
                                )
                            },
                        )
                    }

                    ToolFooter(
                        text = "Generated with SecureRandom, and at least one character comes from " +
                            "every set you switch on. Nothing is saved — close the tool and the " +
                            "password is gone.",
                    )
                }
            }
        }
    }
}
